# -*- coding: utf-8 -*-
"""
Created on Sat Mar  7 18:13:26 2020

@author: Juliano
"""

import scrapy
from lxml import etree
from parsel import Selector
import uuid

class RemuneracionSpider(scrapy.Spider):
    name = 'remuneracion'
    line_titles = []
    selectors = {}
    
    def start_requests(self):
        
        institutions = [("MA031","Asociación de Municipios Ciudad Sur - Asociación Municipal"),
                        ("CM038","Corporación Municipal de Iquique - Corporaciones Municipales"),
                        ("EP017","Empresa Portuaria Iquique - Empresas y Sociedades"),
                        ("MU112","Municipalidad de Iquique - Municipios de Tarapacá"),
                        ("UN002","Universidad Arturo Prat (UNAP) - Universidades"),
                        ("AK010","Corporación de Asistencia Judicial Regiones Tarapacá y Antofagasta (CAJTA) - Justicia"),
                        ("EP027","ZOFRI S.A.  (ZOFRI) - Empresas y Sociedades"),
                        ("AB024","Gobernación de Iquique - Interior y Seguridad Pública"),
                        ("AO017","Servicio de Salud Iquique - Salud"),
                        ("AO040","SEREMI de Salud  de Tarapacá - Salud"),
                        ("PP048","Partido Por La Integración Regional - Partidos Políticos"),
                        ("AO068","Hospital Ernesto Torres de Iquique - Salud"),
                        ("MA013","Asociación de Municipios Rurales Regiones de Tarapacá y AricaParinacota - Asociación Municipal"),
                        ("AB017","Intendencia de Tarapacá - Interior y Seguridad Pública"),
                        ("AB076","Gobierno Regional de Tarapacá - Interior y Seguridad Pública"),
                        ("AP002","SERVIU Región de Tarapacá - Vivienda y Urbanismo"),
                        ("CF003","CFT de la Región del Tarapacá - Centro de Formación Técnica"),
                        ("MU005","Municipalidad de Alto Hospicio - Municipios de Tarapacá"),
                        ("MA057","Asociación de Municipalidades de la Provincia de Iquique Para La Gestión Ambiental y de Residuos - Asociación Municipal"),
                        ("MU226","Municipalidad de Pozo Almonte - Municipios de Tarapacá"),
                        ("CM034","Corporación Municipal de Pozo Almonte - Corporaciones Municipales"),
                        ("AB025","Gobernación de Tamarugal - Interior y Seguridad Pública"),
                        ("MU025","Municipalidad de Camiña - Municipios de Tarapacá"),
                        ("MU056","Municipalidad de Colchane - Municipios de Tarapacá"),
                        ("MU107","Municipalidad de Huara - Municipios de Tarapacá"),
                        ("MU217","Municipalidad de Pica - Municipios de Tarapacá"),
                        ("AO090","Hospital de Puerto Montt - Salud"),
                        ("AB087","Gobierno Regional de Los Lagos (Gore Los Lagos) - Interior y Seguridad Pública"),
                        ("AO037","Servicio de Salud del Reloncaví - Salud"),
                        ("AB058","Gobernación de Llanquihue - Interior y Seguridad Pública"),
                        ("AP012","SERVIU Región de Los Lagos - Vivienda y Urbanismo"),
                        ("EP018","Empresa Portuaria Puerto Montt - Empresas y Sociedades"),
                        ("AB013","Intendencia de Los Lagos - Interior y Seguridad Pública"),
                        ("AO051","SEREMI de Salud de Los Lagos - Salud"),
                        ("MU233","Municipalidad de Puerto Montt - Municipios de Los Lagos"),
                        ("AP015","SERVIU Región de Los Ríos - Vivienda y Urbanismo"),
                        ("MU020","Municipalidad de Calbuco - Municipios de Los Lagos"),
                        ("MU049","Municipalidad de Cochamó - Municipios de Los Lagos"),
                        ("MU093","Municipalidad de Fresia - Municipios de Los Lagos"),
                        ("MU094","Municipalidad de Frutillar - Municipios de Los Lagos"),
                        ("MU155","Municipalidad de Los Muermos - Municipios de Los Lagos"),
                        ("MU142","Municipalidad de Llanquihue - Municipios de Los Lagos"),
                        ("CF005","CFT de la Región de los Lagos - Centro de Formación Técnica"),
                        ("MU170","Municipalidad de Maullín - Municipios de Los Lagos"),
                        ("MA025","Asociación Municipalidades Provincia de Llanquihue Para Manejo Sustentable de Residuos y Gestión Ambiental - Asociación Municipal"),
                        ("MA017","Asociación de Municipalidades Desarrollo Apicultura Turismo y Medio Ambiente Zona de Amortiguación de la Región de Los Lagos - Asociación Municipal"),
                        ("MU236","Municipalidad de Puerto Varas - Municipios de Los Lagos"),
                        ("CM011","Corporación Municipal de Castro - Corporaciones Municipales"),
                        ("AO061","Hospital Dr. Augusto Riffart de Castro - Salud"),
                        ("AO035","Servicio de Salud de Chiloé - Salud"),
                        ("AB059","Gobernación de Chiloé - Interior y Seguridad Pública"),
                        ("MU031","Municipalidad de Castro - Municipios de Los Lagos"),
                        ("MU006","Municipalidad de Ancud - Municipios de Los Lagos"),
                        ("MA032","Asociación de Municipios de Desarrollo Intercomunal de Chiloé - Asociación Municipal"),
                        ("CM024","Corporación Municipal de Ancud - Corporaciones Municipales"),
                        ("CM020","Corporación de Educación Salud y Atención de Menores Chonchi Chiloé - Corporaciones Municipales"),
                        ("MU046","Municipalidad de Chonchi - Municipios de Los Lagos"),
                        ("CM037","Corporación Municipal de Curaco De Velez - Corporaciones Municipales"),
                        ("MU074","Municipalidad de Curaco de Vélez - Municipios de Los Lagos"),
                        ("MU079","Municipalidad de Dalcahue - Municipios de Los Lagos"),
                        ("CM012","Corporación Municipal de Educación y Servicios Ramón Freire Dalcahue - Corporaciones Municipales"),
                        ("MU240","Municipalidad de Puqueldón - Municipios de Los Lagos"),
                        ("CM006","Corporación Municipal de Puqueldón - Corporaciones Municipales"),
                        ("MU246","Municipalidad de Queilén - Municipios de Los Lagos"),
                        ("CM004","Corporación Municipal de Queilen - Corporaciones Municipales"),
                        ("MU247","Municipalidad de Quellón - Municipios de Los Lagos"),
                        ("CM013","Corporación Municipal de Quellón - Corporaciones Municipales"),
                        ("MU248","Municipalidad de Quemchi - Municipios de Los Lagos"),
                        ("CM047","Corporación Municipal de Quinchao - Corporaciones Municipales"),
                        ("MU255","Municipalidad de Quinchao - Municipios de Los Lagos"),
                        ("MA024","Asociación de Municipalidades de la Provincia de Osorno para el Manejo Sustentable de Residuos y la Gestión Ambiental - Asociación Municipal"),
                        ("UN015","Universidad de Los Lagos - Universidades"),
                        ("AO034","Servicio de Salud Osorno - Salud"),
                        ("AO089","Hospital de Osorno - Salud"),
                        ("MU191","Municipalidad de Osorno - Municipios de Los Lagos"),
                        ("AB057","Gobernación de Osorno - Interior y Seguridad Pública"),
                        ("MA052","Asociación de Municipalidades de la cuenca del Lago Llanquihue - Asociación Municipal"),
                        ("MU235","Municipalidad de Puerto Octay - Municipios de Los Lagos"),
                        ("MU242","Municipalidad de Purranque - Municipios de Los Lagos"),
                        ("MU245","Municipalidad de Puyehue - Municipios de Los Lagos"),
                        ("MU274","Municipalidad de Río Negro - Municipios de Los Lagos"),
                        ("MU293","Municipalidad de San Juan de la Costa - Municipios de Los Lagos"),
                        ("MU296","Municipalidad de San Pablo - Municipios de Los Lagos"),
                        ("MU036","Municipalidad de Chaitén - Municipios de Los Lagos"),
                        ("AB060","Gobernación de Palena - Interior y Seguridad Pública"),
                        ("MU095","Municipalidad de Futaleufú - Municipios de Los Lagos"),
                        ("MU103","Municipalidad de Hualaihué - Municipios de Los Lagos"),
                        ("MU198","Municipalidad de Palena - Municipios de Los Lagos"),
                        ("AO036","Servicio de Salud Aysén - Salud"),
                        ("AP013","SERVIU Región de Aysén del General Carlos Ibáñez del Campo - Vivienda y Urbanismo"),
                        ("AB088","Gobierno Regional de Aysén (GORE Aysén) - Interior y Seguridad Pública"),
                        ("AB010","Intendencia de Aysén - Interior y Seguridad Pública"),
                        ("AB061","Gobernación de Coyhaique - Interior y Seguridad Pública"),
                        ("AO052","SEREMI de Salud de Aysén - Salud"),
                        ("MU070","Municipalidad de Coyhaique - Municipios de Aysen del General Carlos Ibáñez del Campo"),
                        ("UN017","Universidad de Aysén - Universidades"),
                        ("AO059","Hospital Regional Coyhaique - Salud"),
                        ("MU129","Municipalidad de Lago Verde - Municipios de Aysen del General Carlos Ibáñez del Campo"),
                        ("MA039","Asociación de Municipalidades Región de Aysén - Asociación Municipal"),
                        ("EP015","Empresa Portuaria Chacabuco - Empresas y Sociedades"),
                        ("AB062","Gobernación de Puerto Aysén - Interior y Seguridad Pública"),
                        ("MU013","Municipalidad de Aysen - Municipios de Aysen del General Carlos Ibáñez del Campo"),
                        ("MU047","Municipalidad de Cisnes - Municipios de Aysen del General Carlos Ibáñez del Campo"),
                        ("MU101","Municipalidad de Guaitecas - Municipios de Aysen del General Carlos Ibáñez del Campo"),
                        ("MU050","Municipalidad de Cochrane - Municipios de Aysen del General Carlos Ibáñez del Campo"),
                        ("AB064","Gobernación de Capitán Prat - Interior y Seguridad Pública"),
                        ("MU187","Municipalidad de OHiggins - Municipios de Aysen del General Carlos Ibáñez del Campo"),
                        ("MU326","Municipalidad de Tortel - Municipios de Aysen del General Carlos Ibáñez del Campo"),
                        ("MU041","Municipalidad de Chile Chico - Municipios de Aysen del General Carlos Ibáñez del Campo"),
                        ("AB063","Gobernación de General Carrera - Interior y Seguridad Pública"),
                        ("MU273","Municipalidad de Río Ibáñez - Municipios de Aysen del General Carlos Ibáñez del Campo"),
                        ("AP014","SERVIU Región de Magallanes y la Antártica Chilena - Vivienda y Urbanismo"),
                        ("AO053","SEREMI de Salud de Magallanes y Antártica Chilena - Salud"),
                        ("AB089","Gobierno Regional de Magallanes y de la Antártica Chilena (GORE Magallanes) - Interior y Seguridad Pública"),
                        ("MU239","Municipalidad de Punta Arenas - Municipios de Magallanes y de la Antártica Chilena"),
                        ("EP014","Empresa Portuaria Austral - Empresas y Sociedades"),
                        ("AB015","Intendencia de Magallanes - Interior y Seguridad Pública"),
                        ("AO038","Servicio de Salud Magallanes - Salud"),
                        ("MA019","Asociación Regional de Municipalidades de Magallanes y Antártica Chilena (AMUMAG) - Asociación Municipal"),
                        ("UN016","Universidad de Magallanes - Universidades"),
                        ("AC005","Instituto Antártico Chileno (INACH) - Relaciones Exteriores"),
                        ("AO082","Hospital Clínico Magallanes Dr Lautaro Navarro Aravia - Salud"),
                        ("CM046","Corporación Municipal de Punta Arenas (CORMUPA) - Corporaciones Municipales"),
                        ("AB066","Gobernación de Magallanes - Interior y Seguridad Pública"),
                        ("MU130","Municipalidad de Laguna Blanca - Municipios de Magallanes y de la Antártica Chilena"),
                        ("MU275","Municipalidad de Río Verde - Municipios de Magallanes y de la Antártica Chilena"),
                        ("MU288","Municipalidad de San Gregorio - Municipios de Magallanes y de la Antártica Chilena"),
                        ("MU017","Municipalidad de Cabo de Hornos y Antártica - Municipios de Magallanes y de la Antártica Chilena"),
                        ("AB068","Gobernación de La Antártica Chilena - Interior y Seguridad Pública"),
                        ("AB067","Gobernación de Tierra del Fuego - Interior y Seguridad Pública"),
                        ("MU225","Municipalidad de Porvenir - Municipios de Magallanes y de la Antártica Chilena"),
                        ("MU227","Municipalidad de Primavera - Municipios de Magallanes y de la Antártica Chilena"),
                        ("MU320","Municipalidad de Timaukel - Municipios de Magallanes y de la Antártica Chilena"),
                        ("CM045","Corporación Municipal de Puerto Natales - Corporaciones Municipales"),
                        ("AB065","Gobernación de última Esperanza - Interior y Seguridad Pública"),
                        ("MU234","Municipalidad de Puerto Natales - Municipios de Magallanes y de la Antártica Chilena"),
                        ("MU325","Municipalidad de Torres del Paine - Municipios de Magallanes y de la Antártica Chilena"),
                        ("AO004","Fondo Nacional de Salud (FONASA) - Salud"),
                        ("AR005","Oficinas de Estudios y Políticas Agrarias (ODEPA) - Agricultura"),
                        ("AD012","Defensa Civil de Chile - Defensa Nacional"),
                        ("AC004","AGENCIA CHILENA DE COOPERACIÓN INTERNACIONAL PARA EL DESARROLLO (AGCID) - Relaciones Exteriores"),
                        ("PP040","Partido Izquierda Ciudadana - Partidos Políticos"),
                        ("PP039","Partido Igualdad (PI) - Partidos Políticos"),
                        ("AM010","Dirección de Vialidad (VIALIDAD) - Obras Públicas"),
                        ("AW004","Servicio de Evaluación Ambiental (SEA) - Medio Ambiente"),
                        ("AK008","Corporación de Asistencia Judicial de la Región Metropolitana (CAJMETRO) - Justicia"),
                        ("AE009","Comisión para el Mercado Financiero (CMF  ex SVS) - Hacienda"),
                        ("AR001","Subsecretaría de Agricultura - Agricultura"),
                        ("PP047","Partido de Trabajadores Revolucionarios - Partidos Políticos"),
                        ("PP027","Partido Poder Ciudadano - Partidos Políticos"),
                        ("AB002","Subsecretaría de Desarrollo Regional (SUBDERE) - Interior y Seguridad Pública"),
                        ("AJ008","Comisión Nacional de Investigación Científica y Tecnológica (CONICYT) - Educación"),
                        ("AE013","Administradora de los Tribunales Tributarios y Aduaneros (ATTA) - Hacienda"),
                        ("AB004","Oficina Nacional de Emergencia (ONEMI) - Interior y Seguridad Pública"),
                        ("EP029","Comercializadora de Trigo COTRISA - Empresas y Sociedades"),
                        ("AH001","Subsecretaría de Economía (MINECON) - Economía Fomento y Turismo"),
                        ("AO075","Hospital San Juan de Dios - Salud"),
                        ("BD001","Subsecretaría de Ciencia Tecnología Conocimiento e Innovación - Ciencia Tecnología e Innovación"),
                        ("AP001","Subsecretaría de Vivienda y Urbanismo (MINVU) - Vivienda y Urbanismo"),
                        ("AO069","Hospital Urgencia Asistencia Pública (HUAP) - Salud"),
                        ("AS002","Comisión Chilena del Cobre (COCHILCO) - Minería"),
                        ("AC002","Dirección General de Relaciones Económicas Internacionales (DIRECON) - Relaciones Exteriores"),
                        ("AH007","Instituto Nacional de Estadisticas (INE) - Economía Fomento y Turismo"),
                        ("AJ005","Dirección de Bibliotecas Archivos y Museos (DIBAM) - Educación"),
                        ("FU003","Fundación para la Promoción y Desarrollo de la Mujer  (PROdeMU) - Fundaciones y corporaciones"),
                        ("FU005","Fundación Artesanías de Chile - Fundaciones y corporaciones"),
                        ("EP007","Empresa de Ferrocarriles del Estado (EFE) - Empresas y Sociedades"),
                        ("AD019","Servicio Hidrográfico y Oceanográfico de La Armada (SHOA) - Defensa Nacional"),
                        ("UN008","Universidad de Santiago de Chile (USACH) - Universidades"),
                        ("AM009","Dirección de Planeamiento (DIRPLAN) - Obras Públicas"),
                        ("AB006","Servicio Electoral (SERVEL) - Servicio Electoral"),
                        ("EP025","Sistema de Empresas Públicas (SEP) - Empresas y Sociedades"),
                        ("AM008","Dirección de Obras Portuarias (DOP) - Obras Públicas"),
                        ("NR007","Tribunal Constitucional (TC) - Tribunal Constitucional"),
                        ("EP004","Empresa Concesionaria de Servicios Sanitarios (ECONSSA) - Empresas y Sociedades"),
                        ("NR001","Poder Judicial - Poder Judicial"),
                        ("EP009","Empresa Nacional de Minería (ENAMI) - Empresas y Sociedades"),
                        ("AE006","Servicio de Impuestos Internos (SII) - Hacienda"),
                        ("EP005","Empresa de Abastecimiento de Zonas Aisladas (EMAZA) - Empresas y Sociedades"),
                        ("EP003","Corporación Nacional del Cobre de Chile (CODELCO) - Empresas y Sociedades"),
                        ("AM003","Dirección de Contabilidad y Finanzas (DCYF) - Obras Públicas"),
                        ("AU004","Superintendencia de Electricidad y Combustibles (SEC) - Energía"),
                        ("EP023","METRO S.A. - Empresas y Sociedades"),
                        ("AH014","Tribunal de Propiedad Industrial (TDPI) - Economía Fomento y Turismo"),
                        ("AR009","Fundación de Comunicación Capacitación y Cultura del Agro (FUCOA) - Agricultura"),
                        ("AJ007","Consejo de Calificación Cinematográfica - Educación"),
                        ("AD018","Servicio Aerofotogramétrico FACH (SAF) - Defensa Nacional"),
                        ("UN009","Universidad Tecnológica Metropolitana (UTEM) - Universidades"),
                        ("AL005","Instituto de Previsión Social (IPS) - Trabajo y Previsión Social"),
                        ("AD006","Ejército de Chile - Defensa Nacional"),
                        ("AM002","Dirección General de Obras Públicas (DGOP) - Obras Públicas"),
                        ("AM007","Dirección de Obras Hidráulicas (DOH) - Obras Públicas"),
                        ("EP008","Empresa Nacional de Aeronáutica de Chile - Empresas y Sociedades"),
                        ("PP022","Partido Radical de Chile - Partidos Políticos"),
                        ("MA001","Asociación de Municipalidades Rurales de la Región Metropolitana de Santiago (AMUR) - Asociación Municipal"),
                        ("AI006","Servicio Nacional del Adulto Mayor (SENAMA) - Desarrollo Social"),
                        ("AJ014","Subsecretaría de Educación Parvularia - Educación"),
                        ("AL008","Superintendencia de Pensiones (SP) - Trabajo y Previsión Social"),
                        ("AN003","Junta de Aeronáutica Civil (JAC) - Transportes y Telecomunicaciones"),
                        ("AR006","Servicio Agrícola y Ganadero (SAG) - Agricultura"),
                        ("AL010","Comisión del Sistema Nacional de Certificación de Competencias Laborales (CHILEVALORA) - Trabajo y Previsión Social"),
                        ("AD009","Carabineros de Chile - Interior y Seguridad Pública"),
                        ("EP011","Empresa Nacional del Petróleo (ENAP) - Empresas y Sociedades"),
                        ("EP006","Empresa de Correos de Chile (CORREOS) - Empresas y Sociedades"),
                        ("AW002","Subsecretaría del Medio Ambiente (MMA) - Medio Ambiente"),
                        ("EP024","Polla Chilena de Beneficencia S.A. - Empresas y Sociedades"),
                        ("AC001","Subsecretaría de Relaciones Exteriores (MINREL) - Relaciones Exteriores"),
                        ("AT001","Servicio Nacional de la Mujer y la Equidad de Género (SERNAMEG) - La Mujer y Equidad de Género"),
                        ("AO107","Instituto Traumatológico - Salud"),
                        ("AO071","Hospital San José - Salud"),
                        ("EP002","Banco del Estado de Chile (BANCO ESTADO) - Empresas y Sociedades"),
                        ("UN010","Universidad de Chile (UCHILE) - Universidades"),
                        ("BB001","Subsecretaría de la Mujer y la Equidad de Género - La Mujer y Equidad de Género"),
                        ("AM001","Subsecretaría de Obras Públicas (MOP) - Obras Públicas"),
                        ("AM012","Instituto Nacional de Hidráulica (INH) - Instituto Nacional de Hidráulica (INH)"),
                        ("AK004","Servicio Nacional de Menores (SENAME) - Justicia"),
                        ("AD010","Policía de Investigaciones (PDI) - Interior y Seguridad Pública"),
                        ("AB092","Servicio Nacional para la Prevención y Rehabilitación del Consumo de Drogas y Alcohol (SENDA) - Interior y Seguridad Pública"),
                        ("AL006","Instituto de Seguridad Laboral (ISL) - Trabajo y Previsión Social"),
                        ("PP054","Partido Regionalista Independiente Demócrata (PRID) - Partidos Políticos"),
                        ("AB021","Intendencia Metropolitana - Interior y Seguridad Pública"),
                        ("EP030","Empresa de Servicios Sanitarios Lago Peñuelas - Empresas y Sociedades"),
                        ("AO007","Servicio de Salud Metropolitano Central - Salud"),
                        ("AY001","Instituto Nacional de Propiedad Industrial (INAPI) - Economía Fomento y Turismo"),
                        ("PP053","Partido Izquierda Anticapitalista de los Trabajadores (IAT) - Partidos Políticos"),
                        ("PP009","Partido Demócrata Cristiano (PDC) - Partidos Políticos"),
                        ("EP028","Casa de Moneda de Chile - Empresas y Sociedades"),
                        ("PP051","Partido MAS Región - Partidos Políticos"),
                        ("AM011","Superintendencia de Servicios Sanitarios (SISS) - Superintendencia de Servicios Sanitarios"),
                        ("BC003","Servicio Nacional del Patrimonio Cultural - Culturas y las Artes"),
                        ("AE001","Subsecretaría de Hacienda - Hacienda"),
                        ("PP025","Partido Socialista de Chile PS - Partidos Políticos"),
                        ("AK005","Defensoría Penal Pública (DPP) - Justicia"),
                        ("BC002","Subsecretaría del Patrimonio Cultural - Culturas y las Artes"),
                        ("UN011","Universidad Metropolitana de Ciencias de la Educación (UMCE) - Universidades"),
                        ("AO001","Subsecretaría de Salud Pública (MINSAL) - Salud"),
                        ("AM013","Fiscalía MOP - Obras Públicas"),
                        ("AE012","Superintendencia de Casinos de Juego (SCJ) - Hacienda"),
                        ("AH011","Subsecretaría de Turismo - Economía Fomento y Turismo"),
                        ("AO070","Hospital San Borja Arriarán - Salud"),
                        ("AI003","Servicio Nacional de Discapacidad (SENADIS) - Desarrollo Social"),
                        ("AJ012","Agencia de Calidad de la Educación - Educación"),
                        ("AH013","Superintendencia de Insolvencia y Reemprendimiento - Economía Fomento y Turismo"),
                        ("AB005","Servicio de Gobierno Interior - Interior y Seguridad Pública"),
                        ("AI008","Subsecretaría de Servicios Sociales - Desarrollo Social"),
                        ("PP033","Partido Amplitud - Partidos Políticos"),
                        ("AD023","Estado Mayor Conjunto (EMCO) - Defensa Nacional"),
                        ("AB091","Subsecretaría de Prevención del Delito - Interior y Seguridad Pública"),
                        ("AD015","Caja de Previsión de la Defensa Nacional (CAPREDENA) - Defensa Nacional"),
                        ("AI004","Fondo de Solidaridad e Inversión Social (FOSIS) - Desarrollo Social"),
                        ("AL003","Dirección del Trabajo (DT) - Trabajo y Previsión Social"),
                        ("AH003","Agencia de Promoción de la Inversión Extranjera - Economía Fomento y Turismo"),
                        ("AL001","Subsecretaría del Trabajo (MINTRAB) - Trabajo y Previsión Social"),
                        ("FU006","Fundación de las Familias - Fundaciones y corporaciones"),
                        ("AX001","Consejo de Defensa del Estado (CDE) - Consejo Defensa del Estado"),
                        ("AO009","Servicio de Salud Metropolitano Occidente - Salud"),
                        ("AL004","Dirección General de Crédito Prendario (DICREP) - Trabajo y Previsión Social"),
                        ("PP019","Partido Por la Democracia (PPD) - Partidos Políticos"),
                        ("AU001","Comisión Nacional de Energía (CNE) - Energía"),
                        ("AG001","Subsecretaría General de Gobierno (SEGEGOB) - Secretaría General de Gobierno"),
                        ("AE005","Unidad de Análisis Financiero - Hacienda"),
                        ("AU002","Subsecretaría de Energía - Energía"),
                        ("MA007","Asociación Chilena de Municipalidades - Asociación Municipal"),
                        ("AE008","Superintendencia de Bancos e Instituciones Financieras (SBIF) - Hacienda"),
                        ("AK001","Subsecretaría de Justicia - Justicia"),
                        ("EP022","Fábricas y Maestranzas del Ejército (FAMAE) - Empresas y Sociedades"),
                        ("AQ001","Subsecretaría de Bienes Nacionales - Bienes Nacionales"),
                        ("AH004","Corporación de Fomento Para La Producción (CORFO) - Economía Fomento y Turismo"),
                        ("AI009","Subsecretaría de la Niñez - Desarrollo Social"),
                        ("PP032","Partido Liberal de Chile(PLCH) - Partidos Políticos"),
                        ("AJ025","Subsecretaría de Educación Superior - Educación"),
                        ("AE002","Dirección de Presupuestos (DIPRES) - Hacienda"),
                        ("AL007","Servicio Nacional de Capacitación y Empleo (SENCE) - Trabajo y Previsión Social"),
                        ("AP007","SERVIU Región Metropolitana de Santiago - Vivienda y Urbanismo"),
                        ("AC007","Subsecretaría de Relaciones Económicas Internacionales - Relaciones Exteriores"),
                        ("AJ002","Consejo de Rectores - Educación"),
                        ("AE004","Dirección Nacional del Servicio Civil - Hacienda"),
                        ("AU003","Comisión Chilena de Energía Nuclear (CCHEN) - Energía"),
                        ("AI005","Instituto Nacional de la Juventud (INJUV) - Desarrollo Social"),
                        ("EP032","Centro de Investigación Minera y Metalúrgica - Empresas y Sociedades"),
                        ("AR004","Instituto de Desarrollo Agropecuario (INDAP) - Agricultura"),
                        ("AE011","Dirección de Compras y Contratación Pública (CHILECOMPRA) - Hacienda"),
                        ("AR003","Corporación Nacional Forestal (CONAF) - Agricultura"),
                        ("AJ001","Subsecretaría de Educación (MINEDUC) - Educación"),
                        ("AW003","Superintendencia del Medio Ambiente (SMA) - Medio Ambiente"),
                        ("AJ021","Superintendencia de Educación Superior - Educación"),
                        ("AO045","SEREMI de Salud  Metropolitano de Santiago - Salud"),
                        ("FU001","Fundación Integra - Fundaciones y corporaciones"),
                        ("AD013","Dirección General de Movilización Nacional (DGMN) - Defensa Nacional"),
                        ("AJ018","Dirección de Educación Pública - Educación"),
                        ("AN001","Subsecretaría de Transportes (MTT) - Transportes y Telecomunicaciones"),
                        ("AB081","Gobierno Regional Metropolitano de Santiago  (GORE Metropolitano) - Interior y Seguridad Pública"),
                        ("CT001","Consejo para la Transparencia (CPLT) - Consejo para la Transparencia"),
                        ("AM004","Dirección de Aeropuertos (DAP) - Obras Públicas"),
                        ("AS001","Subsecretaría de Minería - Minería"),
                        ("AL002","Subsecretaría de Previsión Social (SPS) - Trabajo y Previsión Social"),
                        ("AM005","Dirección de Arquitectura (DARQ) - Obras Públicas"),
                        ("AK012","Subsecretaria de Derechos Humanos - Justicia"),
                        ("AD021","Subsecretaría de Defensa - Defensa Nacional"),
                        ("AE003","Tesorería General de la República (TGR) - Hacienda"),
                        ("AD016","Dirección de Previsión de Carabineros de Chile (DIPRECA) - Interior y Seguridad Pública"),
                        ("AF001","Subsecretaría General de La Presidencia (SEGPRES) - Secretaría General de la Presidencia"),
                        ("AA001","Presidencia de la República - Presidencia de la República"),
                        ("AI001","Subsecretaria de Evaluación Social - Desarrollo Social"),
                        ("AJ011","Superintendencia de Educación - Educación"),
                        ("AH005","Fiscalía Nacional Económica (FNE) - Economía Fomento y Turismo"),
                        ("MA047","Asociación de Municipalidades con Centros de Montaña - Asociación Municipal"),
                        ("PP007","Partido Comunista de Chile (PCCH) - Partidos Políticos"),
                        ("AH012","Servicio de Cooperación Técnica (SERCOTEC) - Economía Fomento y Turismo"),
                        ("AM014","Dirección General de Concesiones de Obras Públicas (DGC) - Obras Públicas"),
                        ("AH008","Servicio Nacional de Turismo (SERNATUR) - Economía Fomento y Turismo"),
                        ("AR010","Centro de Información de Recursos Naturales (CIREN) - Agricultura"),
                        ("AD022","Subsecretaría para las Fuerzas Armadas (SSFFAA) - Defensa Nacional"),
                        ("AB001","Subsecretaría del Interior - Interior y Seguridad Pública"),
                        ("MU308","Municipalidad de Santiago - Municipios de R. Metropolitana de Santiago"),
                        ("AM006","Dirección General de Aguas (DGA) - Obras Públicas"),
                        ("AH009","Servicio Nacional del Consumidor (SERNAC) - Economía Fomento y Turismo"),
                        ("AR002","Comisión Nacional de Riego (CNR) - Agricultura"),
                        ("AZ001","Comisión Nacional de Acreditación (CNA) - Educación"),
                        ("AL009","Superintendencia de Seguridad Social (SUSESO) - Trabajo y Previsión Social"),
                        ("AK006","Gendarmería de Chile - Justicia"),
                        ("NR002","Contraloría General de la República (CGR) - Contraloría de la República"),
                        ("AB003","Agencia Nacional de Inteligencia (ANI) - Interior y Seguridad Pública"),
                        ("AK002","Servicio de Registro Civil e Identificación - Justicia"),
                        ("AJ009","Junta Nacional de Auxilio Escolar y Becas (JUNAEB) - Educación"),
                        ("AC003","Dirección Nacional de Fronteras y Límites del Estado (DIFROL) - Relaciones Exteriores"),
                        ("AO006","Superintendencia de Salud (SdS) - Salud"),
                        ("FU004","Fundación de Orquestas Juveniles e Infantiles de Chile (FOJI) - Fundaciones y corporaciones"),
                        ("AO002","Subsecretaría de Redes Asistenciales - Salud"),
                        ("AN002","Subsecretaría de Telecomunicaciones (SUBTEL) - Transportes y Telecomunicaciones"),
                        ("AD007","Armada de Chile - Defensa Nacional"),
                        ("MU034","Municipalidad de Cerrillos - Municipios de R. Metropolitana de Santiago"),
                        ("AD008","Fuerza Aérea de Chile (Incluye al Servicio Aerofotogramétrico) - Defensa Nacional"),
                        ("MU035","Municipalidad de Cerro Navia - Municipios de R. Metropolitana de Santiago"),
                        ("CM022","Corporación Municipal de Cerro Navia - Corporaciones Municipales"),
                        ("MU062","Municipalidad de Conchalí - Municipios de R. Metropolitana de Santiago"),
                        ("MU082","Municipalidad de El Bosque - Municipios de R. Metropolitana de Santiago"),
                        ("MU089","Municipalidad de Estación Central - Municipios de R. Metropolitana de Santiago"),
                        ("MU109","Municipalidad de Huechuraba - Municipios de R. Metropolitana de Santiago"),
                        ("AK003","Servicio Médico Legal (SML) - Justicia"),
                        ("AO072","Hospital Roberto del Río - Salud"),
                        ("MU111","Municipalidad de Independencia - Municipios de R. Metropolitana de Santiago"),
                        ("MA041","Asociación de Municipios Mapocho  La Chimba - Asociación Municipal"),
                        ("AO108","Instituto Nacional del Cáncer - Salud"),
                        ("AO008","Servicio de Salud Metropolitano Norte - Salud"),
                        ("MU117","Municipalidad de La Cisterna - Municipios de R. Metropolitana de Santiago"),
                        ("MA050","Asociación Metropolitana de Municipalidades de Santiago Sur para la Gestión Ambiental y de Residuos (MSUR) - Asociación Municipal"),
                        ("MU120","Municipalidad de La Florida - Municipios de R. Metropolitana de Santiago"),
                        ("CM027","Corporación Municipal de La Florida - Corporaciones Municipales"),
                        ("FU002","Fundación Tiempos Nuevos (MIM) - Fundaciones y corporaciones"),
                        ("MU121","Municipalidad de La Granja - Municipios de R. Metropolitana de Santiago"),
                        ("MU124","Municipalidad de La Pintana - Municipios de R. Metropolitana de Santiago"),
                        ("MU125","Municipalidad de La Reina - Municipios de R. Metropolitana de Santiago"),
                        ("AR007","Fundación para la Innovación Agraria (FIA) - Agricultura"),
                        ("MA006","Asociación de Municipalidades Parque Cordillera - Asociación Municipal"),
                        ("CM017","Corporación Municipal de La Reina - Corporaciones Municipales"),
                        ("PP031","Partido Todos - Partidos Políticos"),
                        ("MA009","Asociación de Municipalidades de la Zona Oriente de la Región Metropolitana - Asociación Municipal"),
                        ("CM021","Corporación Municipal de Las Condes - Corporaciones Municipales"),
                        ("MU135","Municipalidad de Las Condes - Municipios de R. Metropolitana de Santiago"),
                        ("PP030","Partido Ciudadanos - Partidos Políticos"),
                        ("MU144","Municipalidad de Lo Barnechea - Municipios de R. Metropolitana de Santiago"),
                        ("MA051","Asociación de Municipalidades para la Seguridad Ciudadana en la Zona Oriente - Asociación Municipal"),
                        ("MU145","Municipalidad de Lo Espejo - Municipios de R. Metropolitana de Santiago"),
                        ("CM040","Corporación Municipal de Lo Prado - Corporaciones Municipales"),
                        ("AJ016","Servicio Local de Educación Pública de Barrancas - Educación"),
                        ("MU146","Municipalidad de Lo Prado - Municipios de R. Metropolitana de Santiago"),
                        ("CM041","Corporación Municipal de Macul - Corporaciones Municipales"),
                        ("MU161","Municipalidad de Macul - Municipios de R. Metropolitana de Santiago"),
                        ("AO111","Hospital El Carmen Dr. Luis Valentín Ferrada - Salud"),
                        ("MU163","Municipalidad de Maipú - Municipios de R. Metropolitana de Santiago"),
                        ("AO015","Centro de Referencia de Salud de Maipú (CRSM) - Salud"),
                        ("CM007","Corporación Municipal de Maipú (CODEDUC) - Corporaciones Municipales"),
                        ("AO003","Central de Abastecimiento del Sistema Nacional de Servicios de Salud (CENABAST) - Salud"),
                        ("AR011","Instituto Forestal (INFOR) - Agricultura"),
                        ("MU186","Municipalidad de Ñuñoa - Municipios de R. Metropolitana de Santiago"),
                        ("CM001","Corporación Municipal de Desarrollo Social de Ñuñoa - Corporaciones Municipales"),
                        ("AO005","Instituto de Salud Pública (ISP) - Salud"),
                        ("MU205","Municipalidad de Pedro Aguirre Cerda - Municipios de R. Metropolitana de Santiago"),
                        ("CM005","Corporación Municipal de Peñalolén (CORMUP) - Corporaciones Municipales"),
                        ("AO106","Hospital Luis Tisné - Salud"),
                        ("AO076","Instituto Nacional de Rehabilitación Pedro Aguirre Cerda - Salud"),
                        ("AO014","Centro de Referencia de Salud de Peñalolén Cordillera Oriente (CRSORIENTE) - Salud"),
                        ("MU212","Municipalidad de Peñalolén - Municipios de R. Metropolitana de Santiago"),
                        ("PP029","Partido Revolución Democrática (RD) - Partidos Políticos"),
                        ("MU228","Municipalidad de Providencia - Municipios de R. Metropolitana de Santiago"),
                        ("PP014","Partido Humanista (PH) - Partidos Políticos"),
                        ("MA056","Asociación de Municipios Metropolitanos para la Seguridad Ciudadana (AMMSeguridad) - Asociación Municipal"),
                        ("AR008","Instituto de Investigaciones Agropecuarias (INIA) - Agricultura"),
                        ("PP028","Partido Renovación Nacional (RN) - Partidos Políticos"),
                        ("AO109","Hospital Luis Calvo Mackenna - Salud"),
                        ("PP011","Partido Evolución Política (Evópoli) - Partidos Políticos"),
                        ("AC006","Dirección General de Promoción de Exportaciones - Relaciones Exteriores"),
                        ("CO001","Instituto Nacional de Derechos Humanos (INDH) - Instituto Derechos Humanos"),
                        ("AO077","Instituto de Neurocirugía - Salud"),
                        ("AG003","Consejo Nacional de Televisión (CNTV) - Secretaría General de Gobierno"),
                        ("EP026","Televisión Nacional de Chile (TVN) - Empresas y Sociedades"),
                        ("CM031","Corporación Municipal de Providencia - Corporaciones Municipales"),
                        ("AJ003","Consejo Nacional de Educación (CNED) - Educación"),
                        ("AD020","Dirección General de Aeronáutica Civil (DGAC) - Defensa Nacional"),
                        ("AO078","Instituto Nacional de Geriatría (ING) - Salud"),
                        ("AJ004","Comisión Administradora del Sistema de Créditos para Estudios Superiores (INGRESA) - Educación"),
                        ("PP021","Partido Progresista (PRO) - Partidos Políticos"),
                        ("BA001","Subsecretaría del Deporte - Deporte"),
                        ("AJ010","Junta Nacional de Jardines Infantiles (JUNJI) - Educación"),
                        ("PP034","Partido Federación Regionalista Verde Social  (FREVS) - Partidos Políticos"),
                        ("MA018","Asociación de Municipalidades de Chile AMUCH - Asociación Municipal"),
                        ("PP052","Partido Pais Progresista - Partidos Políticos"),
                        ("AO079","Hospital del Salvador - Salud"),
                        ("BA002","Instituto Nacional del Deporte (IND) - Deporte"),
                        ("AS004","Servicio Nacional de Geología y Minería (SERNAGEOMIN) - Minería"),
                        ("FU008","Fundación Cultural Providencia - Fundaciones y corporaciones"),
                        ("AO010","Servicio de Salud Metropolitano Oriente - Salud"),
                        ("PP026","Partido Unión Demócrata Independiente  UDI - Partidos Políticos"),
                        ("AO105","Instituto Nacional del Tórax - Salud"),
                        ("CO005","Defensoría de los Derechos de la Niñez - Defensoría de los Derechos de la Niñez"),
                        ("CM032","Corporación Municipal de Pudahuel - Corporaciones Municipales"),
                        ("MU231","Municipalidad de Pudahuel - Municipios de R. Metropolitana de Santiago"),
                        ("MU250","Municipalidad de Quilicura - Municipios de R. Metropolitana de Santiago"),
                        ("FU007","Fundación Chilenter - Fundaciones y corporaciones"),
                        ("CM029","Corporación Municipal de Quinta Normal - Corporaciones Municipales"),
                        ("MU257","Municipalidad de Quinta Normal - Municipios de R. Metropolitana de Santiago"),
                        ("AO073","Hospital Félix Bulnes - Salud"),
                        ("MU263","Municipalidad de Recoleta - Municipios de R. Metropolitana de Santiago"),
                        ("CM036","Corporación Municipal de Conchali - Corporaciones Municipales"),
                        ("AP017","Parque Metropolitano de Santiago - Vivienda y Urbanismo"),
                        ("AO100","Instituto Psiquiátrico - Salud"),
                        ("MA053","Asociación Chilena de Municipalidades con Farmacias Populares (ACHIFARP) - Asociación Municipal"),
                        ("MU265","Municipalidad de Renca - Municipios de R. Metropolitana de Santiago"),
                        ("CM048","Corporación Municipal de Renca - Corporaciones Municipales"),
                        ("CM030","Corporación Municipal de San Joaquin - Corporaciones Municipales"),
                        ("MU291","Municipalidad de San Joaquín - Municipios de R. Metropolitana de Santiago"),
                        ("AO102","Hospital Exequiel González - Salud"),
                        ("CM050","Corporación Municipal de San Miguel - Corporaciones Municipales"),
                        ("AO080","Hospital Barros Luco - Salud"),
                        ("AO011","Servicio de Salud Metropolitano Sur - Salud"),
                        ("MU294","Municipalidad de San Miguel - Municipios de R. Metropolitana de Santiago"),
                        ("AO013","Hospital Padre Hurtado - Salud"),
                        ("MU301","Municipalidad de San Ramón - Municipios de R. Metropolitana de Santiago"),
                        ("MU341","Municipalidad de Vitacura - Municipios de R. Metropolitana de Santiago"),
                        ("MA027","Asociación Municipal para la sustentabilidad ambiental AMUSA - Asociación Municipal"),
                        ("AB070","Gobernación de Cordillera - Interior y Seguridad Pública"),
                        ("CM044","Corporación Municipal de Puente Alto - Corporaciones Municipales"),
                        ("AO081","Hospital Sótero del Río - Salud"),
                        ("MU232","Municipalidad de Puente Alto - Municipios de R. Metropolitana de Santiago"),
                        ("AO012","Servicio de Salud Metropolitano Sur Oriente - Salud"),
                        ("CM014","Corporación Municipal de Pirque - Corporaciones Municipales"),
                        ("MU221","Municipalidad de Pirque - Municipios de R. Metropolitana de Santiago"),
                        ("CM049","Corporación Municipal de San Jose De Maipo - Corporaciones Municipales"),
                        ("MU292","Municipalidad de San José de Maipo - Municipios de R. Metropolitana de Santiago"),
                        ("MU057","Municipalidad de Colina - Municipios de R. Metropolitana de Santiago"),
                        ("CM026","Corporación Municipal de Colina - Corporaciones Municipales"),
                        ("AB069","Gobernación de Chacabuco - Interior y Seguridad Pública"),
                        ("CM023","Corporación Municipal del Desarrollo Social de Lampa - Corporaciones Municipales"),
                        ("MU132","Municipalidad de Lampa - Municipios de R. Metropolitana de Santiago"),
                        ("MU319","Municipalidad de Tiltil - Municipios de R. Metropolitana de Santiago"),
                        ("CM016","Corporación Municipal de Desarrollo Social de Til Til - Corporaciones Municipales"),
                        ("MU281","Municipalidad de San Bernardo - Municipios de R. Metropolitana de Santiago"),
                        ("CM033","Corporación Municipal de San Bernardo - Corporaciones Municipales"),
                        ("AB071","Gobernación de Maipo - Interior y Seguridad Pública"),
                        ("PP049","Partido ANDHA Chile - Partidos Políticos"),
                        ("AO103","Hospital El Pino - Salud"),
                        ("CM055","Corporación Municipal Cultural y Patrimonial de San Bernardo - Corporaciones Municipales"),
                        ("CM025","Corporación Municipal de Buin - Corporaciones Municipales"),
                        ("MU014","Municipalidad de Buin - Municipios de R. Metropolitana de Santiago"),
                        ("CM035","Corporación Municipal de Calera De Tango - Corporaciones Municipales"),
                        ("MU022","Municipalidad de Calera de Tango - Municipios de R. Metropolitana de Santiago"),
                        ("MU197","Municipalidad de Paine - Municipios de R. Metropolitana de Santiago"),
                        ("MU173","Municipalidad de Melipilla - Municipios de R. Metropolitana de Santiago"),
                        ("AB073","Gobernación de Melipilla - Interior y Seguridad Pública"),
                        ("AO074","Hospital de Melipilla - Salud"),
                        ("CM042","Corporación Municipal de Melipilla - Corporaciones Municipales"),
                        ("MA042","Asociación de Municipalidades de la Zona Central y Costa (AMUCC) - Asociación Municipal"),
                        ("MU002","Municipalidad de Alhué - Municipios de R. Metropolitana de Santiago"),
                        ("MU073","Municipalidad de Curacaví - Municipios de R. Metropolitana de Santiago"),
                        ("MU167","Municipalidad de María Pinto - Municipios de R. Metropolitana de Santiago"),
                        ("CM028","Corporación Municipal de Maria Pinto - Corporaciones Municipales"),
                        ("MU297","Municipalidad de San Pedro - Municipios de R. Metropolitana de Santiago"),
                        ("AB072","Gobernación de Talagante - Interior y Seguridad Pública"),
                        ("CM052","Corporación Municipal de Talagante - Corporaciones Municipales"),
                        ("MU311","Municipalidad de Talagante - Municipios de R. Metropolitana de Santiago"),
                        ("MA049","Asociación de Municipalidades del Valle del Maipo - Asociación Municipal"),
                        ("MU084","Municipalidad de El Monte - Municipios de R. Metropolitana de Santiago"),
                        ("CM003","Corporación Municipal Isla de Maipo - Corporaciones Municipales"),
                        ("MU113","Municipalidad de Isla de Maipo - Municipios de R. Metropolitana de Santiago"),
                        ("MU193","Municipalidad de Padre Hurtado - Municipios de R. Metropolitana de Santiago"),
                        ("MU211","Municipalidad de Peñaflor - Municipios de R. Metropolitana de Santiago"),
                        ("MU330","Municipalidad de Valdivia - Municipios de Los Ríos"),
                        ("AB014","Intendencia de Los Ríos - Interior y Seguridad Pública"),
                        ("AB055","Gobernación de Valdivia - Interior y Seguridad Pública"),
                        ("AO093","Hospital Base de Valdivia - Salud"),
                        ("AB086","Gobierno Regional de Los Ríos (GORE de Los Ríos) - Interior y Seguridad Pública"),
                        ("MA004","Asociación de Municipios de La Región de Los Ríos - Asociación Municipal"),
                        ("MA005","Asociación de Municipalidades de la Región de Los Ríos para el Manejo sustentable de Residuos y la Gestión Ambiental - Asociación Municipal"),
                        ("AO050","SEREMI de Salud de Los Ríos - Salud"),
                        ("AO033","Servicio de Salud Valdivia - Salud"),
                        ("MU069","Municipalidad de Corral - Municipios de Los Ríos"),
                        ("MA054","Asociación de Municipios Cordillera de la Costa CorralLa Unión - Asociación Municipal"),
                        ("MU133","Municipalidad de Lanco - Municipios de Los Ríos"),
                        ("MA012","Asociación de Municipalidades Paisajes de Conservación para la Biodiversidad de la Región de Los Ríos - Asociación Municipal"),
                        ("MU154","Municipalidad de Los Lagos - Municipios de Los Ríos"),
                        ("MU162","Municipalidad de Máfil - Municipios de Los Ríos"),
                        ("MU168","Municipalidad de Mariquina - Municipios de Los Ríos"),
                        ("MU196","Municipalidad de Paillaco - Municipios de Los Ríos"),
                        ("CM043","Corporación Municipal de Panguipulli - Corporaciones Municipales"),
                        ("MU200","Municipalidad de Panguipulli - Municipios de Los Ríos"),
                        ("MU127","Municipalidad de La Unión - Municipios de Los Ríos"),
                        ("CF004","CFT de la Región de los Ríos - Centro de Formación Técnica"),
                        ("AB056","Gobernación de Ranco - Interior y Seguridad Pública"),
                        ("MU096","Municipalidad de Futrono - Municipios de Los Ríos"),
                        ("MU128","Municipalidad de Lago Ranco - Municipios de Los Ríos"),
                        ("MU270","Municipalidad de Rio Bueno - Municipios de Los Ríos"),
                        ("AB022","Gobernación de Arica - Interior y Seguridad Pública"),
                        ("AB075","Gobierno Regional de Arica y Parinacota - Interior y Seguridad Pública"),
                        ("AO058","Hospital Juan Noé de Arica - Salud"),
                        ("AO016","Servicio de Salud Arica - Salud"),
                        ("AJ023","Servicio Local de Educación Pública Chinchorro - Educación"),
                        ("UN001","Universidad de Tarapacá - Universidades"),
                        ("EP013","Empresa Portuaria Arica - Empresas y Sociedades"),
                        ("AP016","SERVIU Región de Arica y Parinacota - Vivienda y Urbanismo"),
                        ("AO039","SEREMI de Salud  de Arica y Parinacota - Salud"),
                        ("AB007","Intendencia Arica y Parinacota - Interior y Seguridad Pública"),
                        ("MU012","Municipalidad de Arica - Municipios de Arica y  Parinacota"),
                        ("MU024","Municipalidad de Camarones - Municipios de Arica y  Parinacota"),
                        ("MU244","Municipalidad de Putre - Municipios de Arica y  Parinacota"),
                        ("AB023","Gobernación de Parinacota - Interior y Seguridad Pública"),
                        ("MU098","Municipalidad de General Lagos - Municipios de Arica y  Parinacota"),
                        ("AB094","Intendencia de Ñuble - Interior y Seguridad Pública"),
                        ("AO104","Hospital Herminda Martin - Salud"),
                        ("AO117","SEREMI de Salud del Ñuble - Salud"),
                        ("AB049","Gobernación de Ñuble (derogada) - Interior y Seguridad Pública"),
                        ("AO026","Servicio de Salud Ñuble - Salud"),
                        ("AB098","Gobierno Regional de Ñuble - Interior y Seguridad Pública"),
                        ("AP018","SERVIU Región del Ñuble - Vivienda y Urbanismo"),
                        ("MU042","Municipalidad de Chillán - Municipios de Ñuble"),
                        ("AB095","Gobernación de Diguillín - Interior y Seguridad Pública"),
                        ("MU015","Municipalidad de Bulnes - Municipios de Ñuble"),
                        ("MA011","Asociación de Municipalidades Territorio de Riego Canal LajaDiguillín - Asociación Municipal"),
                        ("MU043","Municipalidad de Chillán Viejo - Municipios de Ñuble"),
                        ("MU083","Municipalidad de El Carmen - Municipios de Ñuble"),
                        ("MU208","Municipalidad de Pemuco - Municipios de Ñuble"),
                        ("MU220","Municipalidad de Pinto - Municipios de Ñuble"),
                        ("MU252","Municipalidad de Quillón - Municipios de Ñuble"),
                        ("MU289","Municipalidad de San Ignacio - Municipios de Ñuble"),
                        ("MU344","Municipalidad de Yungay - Municipios de Ñuble"),
                        ("MU259","Municipalidad de Quirihue - Municipios de Ñuble"),
                        ("AB097","Gobernación de Itata - Interior y Seguridad Pública"),
                        ("MA040","Asociación de Municipalidades del Valle del Itata - Asociación Municipal"),
                        ("MU048","Municipalidad de Cobquecura - Municipios de Ñuble"),
                        ("MU052","Municipalidad de Coelemu - Municipios de Ñuble"),
                        ("MU182","Municipalidad de Ninhue - Municipios de Ñuble"),
                        ("MU224","Municipalidad de Portezuelo - Municipios de Ñuble"),
                        ("MU261","Municipalidad de Ránquil - Municipios de Ñuble"),
                        ("MU328","Municipalidad de Trehuaco - Municipios de Ñuble"),
                        ("AB096","Gobernación de Punilla - Interior y Seguridad Pública"),
                        ("AO086","Hospital de San Carlos - Salud"),
                        ("MU282","Municipalidad de San Carlos - Municipios de Ñuble"),
                        ("MA022","Asociación de Municipalidades del Punilla - Asociación Municipal"),
                        ("MU053","Municipalidad de Coihueco - Municipios de Ñuble"),
                        ("MU185","Municipalidad de Ñiquén - Municipios de Ñuble"),
                        ("MU285","Municipalidad de San Fabián - Municipios de Ñuble"),
                        ("MU295","Municipalidad de San Nicolás - Municipios de Ñuble"),
                        ("EP012","Empresa Portuaria Antofagasta - Empresas y Sociedades"),
                        ("CM054","Corporación Municipal de Fomento y Desarrollo Comunal de Sierra Gorda - Corporaciones Municipales"),
                        ("AO041","SEREMI de Salud  de Antofagasta - Salud"),
                        ("AO018","Servicio de Salud Antofagasta - Salud"),
                        ("UN003","Universidad de Antofagasta - Universidades"),
                        ("MA002","Asociación de Municipalidades de la Región de Antofagasta - Asociación Municipal"),
                        ("AP003","SERVIU Región de Antofagasta - Vivienda y Urbanismo"),
                        ("AB008","Intendencia de Antofagasta - Interior y Seguridad Pública"),
                        ("AB026","Gobernación de Antofagasta - Interior y Seguridad Pública"),
                        ("AO055","Hospital Leonardo Guzmán de Antofagasta - Salud"),
                        ("MU009","Municipalidad de Antofagasta - Municipios de Antofagasta"),
                        ("CM002","Corporación Municipal de Desarrollo Social de Antofagasta (CMDS) - Corporaciones Municipales"),
                        ("MA020","Asociación de Municipalidades del Norte de Chile - Asociación Municipal"),
                        ("AB077","Gobierno Regional de Antofagasta - Interior y Seguridad Pública"),
                        ("MU171","Municipalidad de Mejillones - Municipios de Antofagasta"),
                        ("MU310","Municipalidad de Sierra Gorda - Municipios de Antofagasta"),
                        ("MU314","Municipalidad de Taltal - Municipios de Antofagasta"),
                        ("CM056","Corporación Municipal de deportes y recreación de Calama (CORMUDEP) - Corporaciones Municipales"),
                        ("CM018","Corporación Municipal de Desarrollo Social de Calama (COMDES) - Corporaciones Municipales"),
                        ("MU019","Municipalidad de Calama - Municipios de Antofagasta"),
                        ("AB027","Gobernación de El Loa - Interior y Seguridad Pública"),
                        ("MU189","Municipalidad de Ollague - Municipios de Antofagasta"),
                        ("MU298","Municipalidad de San Pedro de Atacama - Municipios de Antofagasta"),
                        ("MU322","Municipalidad de Tocopilla - Municipios de Antofagasta"),
                        ("AB028","Gobernación de Tocopilla - Interior y Seguridad Pública"),
                        ("MU166","Municipalidad de María Elena - Municipios de Antofagasta"),
                        ("AO042","SEREMI de Salud  de Atacama - Salud"),
                        ("AP004","SERVIU Región de Atacama - Vivienda y Urbanismo"),
                        ("AB078","Gobierno Regional de Atacama - Interior y Seguridad Pública"),
                        ("AB009","Intendencia de Atacama - Interior y Seguridad Pública"),
                        ("AO019","Servicio de Salud Atacama - Salud"),
                        ("AB030","Gobernación de Copiapó - Interior y Seguridad Pública"),
                        ("MA014","Asociación Regional de Municipios de Atacama - Asociación Municipal"),
                        ("UN004","Universidad de Atacama - Universidades"),
                        ("MU066","Municipalidad de Copiapó - Municipios de Atacama"),
                        ("MU021","Municipalidad de Caldera - Municipios de Atacama"),
                        ("MU318","Municipalidad de Tierra Amarilla - Municipios de Atacama"),
                        ("MU038","Municipalidad de Chañaral - Municipios de Atacama"),
                        ("AB029","Gobernación de Chañaral - Interior y Seguridad Pública"),
                        ("MU080","Municipalidad de Diego de Almagro - Municipios de Atacama"),
                        ("AJ019","Servicio Local de Educación Pública Huasco - Educación"),
                        ("MU331","Municipalidad de Vallenar - Municipios de Atacama"),
                        ("MA046","Asociación de Municipalidades de la Provincia del Huasco - Asociación Municipal"),
                        ("AB031","Gobernación de Huasco - Interior y Seguridad Pública"),
                        ("MU004","Municipalidad de Alto del Carmen - Municipios de Atacama"),
                        ("MU092","Municipalidad de Freirina - Municipios de Atacama"),
                        ("MU108","Municipalidad de Huasco - Municipios de Atacama"),
                        ("AO066","Hospital La Serena - Salud"),
                        ("AO043","SEREMI de Salud  de Coquimbo - Salud"),
                        ("MU126","Municipalidad de La Serena - Municipios de Coquimbo"),
                        ("AP005","SERVIU Región de Coquimbo - Vivienda y Urbanismo"),
                        ("CM039","Corporación Municipal de La Serena - Corporaciones Municipales"),
                        ("AB079","Gobierno Regional de Coquimbo - Interior y Seguridad Pública"),
                        ("AO020","Servicio de Salud Coquimbo - Salud"),
                        ("UN005","Universidad de La Serena - Universidades"),
                        ("MA034","Asociación de Municipalidades Rurales del Norte Chico - Asociación Municipal"),
                        ("EP016","Empresa Portuaria Coquimbo - Empresas y Sociedades"),
                        ("AJ017","Servicio Local de Educación Pública Puerto Cordillera - Educación"),
                        ("AO067","Hospital San Pablo de Coquimbo - Salud"),
                        ("AB032","Gobernación de Elqui - Interior y Seguridad Pública"),
                        ("AB011","Intendencia de Coquimbo - Interior y Seguridad Pública"),
                        ("MA035","Asociación de Municipalidades de la Región de  Coquimbo - Asociación Municipal"),
                        ("MU067","Municipalidad de Coquimbo - Municipios de Coquimbo"),
                        ("MU007","Municipalidad de Andacollo - Municipios de Coquimbo"),
                        ("MU122","Municipalidad de La Higuera - Municipios de Coquimbo"),
                        ("MU195","Municipalidad de Paihuano - Municipios de Coquimbo"),
                        ("MU335","Municipalidad de Vicuña - Municipios de Coquimbo"),
                        ("AB034","Gobernación de Choapa - Interior y Seguridad Pública"),
                        ("MU110","Municipalidad de Illapel - Municipios de Coquimbo"),
                        ("MU026","Municipalidad de Canela - Municipios de Coquimbo"),
                        ("MU157","Municipalidad de Los Vilos - Municipios de Coquimbo"),
                        ("MU279","Municipalidad de Salamanca - Municipios de Coquimbo"),
                        ("CF006","CFT de la Región de Coquimbo - Centro de Formación Técnica"),
                        ("AB033","Gobernación de Limarí - Interior y Seguridad Pública"),
                        ("AO065","Hospital de Ovalle - Salud"),
                        ("MU192","Municipalidad de Ovalle - Municipios de Coquimbo"),
                        ("MU060","Municipalidad de Combarbalá - Municipios de Coquimbo"),
                        ("MU175","Municipalidad de Monte Patria - Municipios de Coquimbo"),
                        ("MU238","Municipalidad de Punitaqui - Municipios de Coquimbo"),
                        ("MU272","Municipalidad de Río Hurtado - Municipios de Coquimbo"),
                        ("AD014","Dirección General del Territorio Marítimo y Marina Mercante (DIRECTEMAR) - Defensa Nacional"),
                        ("AV001","Ex Consejo Nacional de la Cultura y las Artes (CNCA) - Consejo de Cultura y Artes"),
                        ("AO023","Servicio de Salud Viña del Mar  Quillota - Salud"),
                        ("AB018","Intendencia de Valparaíso - Interior y Seguridad Pública"),
                        ("AH015","Instituto Nacional de Desarrollo Sustentable de la Pesca Artesanal y de la Acuicultura de Pequeña Escala (INDESPA) - Economía Fomento y Turismo"),
                        ("UN007","Universidad de Valparaíso - Universidades"),
                        ("MA044","Asociación Nacional de Municipalidades de Ciudades Puerto Concesionados - Asociación Municipal"),
                        ("AK009","Corporación de Asistencia Judicial Región Valparaíso (CAJVAL) - Justicia"),
                        ("BC001","Subsecretaría de las Culturas y las Artes - Culturas y las Artes"),
                        ("AO044","SEREMI de Salud  de Valparaíso - Salud"),
                        ("UN006","Universidad de Playa Ancha (UPLA) - Universidades"),
                        ("MU332","Municipalidad de Valparaíso - Municipios de Valparaíso"),
                        ("AP006","SERVIU Región de Valparaíso - Vivienda y Urbanismo"),
                        ("NR006","Cámara de Diputados - Congreso Nacional"),
                        ("EP021","Empresa Portuaria Valparaíso - Empresas y Sociedades"),
                        ("AH010","Servicio Nacional de Pesca y Acuicultura (SERNAPESCA) - Economía Fomento y Turismo"),
                        ("EP001","Astilleros y Maestranzas de la Armada (ASMAR) - Empresas y Sociedades"),
                        ("AE007","Servicio Nacional de Aduanas - Hacienda"),
                        ("AH002","Subsecretaría de Pesca y Acuicultura - Economía Fomento y Turismo"),
                        ("AO096","Hospital Eduardo Pereira de Valparaíso - Salud"),
                        ("AO095","Hospital Carlos Van Buren - Salud"),
                        ("CM015","Corporación Municipal de Valparaíso - Corporaciones Municipales"),
                        ("NR005","Senado - Congreso Nacional"),
                        ("MA029","Asociación de Municipalidades de Ciudades Puerto y Borde Costero - Asociación Municipal"),
                        ("AB080","Gobierno Regional de Valparaíso  ( GORE Valparaíso) - Interior y Seguridad Pública"),
                        ("AB036","Gobernación de Valparaíso - Interior y Seguridad Pública"),
                        ("NR004","Biblioteca del Congreso Nacional (BCN) - Congreso Nacional"),
                        ("AO022","Servicio de Salud Valparaíso  San Antonio - Salud"),
                        ("MA023","Asociación de Municipalidades de la Región de Valparaíso - Asociación Municipal"),
                        ("MU030","Municipalidad de Casablanca - Municipios de Valparaíso"),
                        ("MU063","Municipalidad de Concón - Municipios de Valparaíso"),
                        ("MU115","Municipalidad de Juan Fernández - Municipios de Valparaíso"),
                        ("MU229","Municipalidad de Puchuncaví - Municipios de Valparaíso"),
                        ("MU258","Municipalidad de Quintero - Municipios de Valparaíso"),
                        ("AO098","Hospital Gustavo Fricke - Salud"),
                        ("MU340","Municipalidad de Viña del Mar - Municipios de Valparaíso"),
                        ("MA030","Asociación de municipalidades con casinos de juegos - Asociación Municipal"),
                        ("CM053","Corporación Municipal de Viña Del Mar - Corporaciones Municipales"),
                        ("MU114","Municipalidad de Isla de Pascua (Rapa Nui) - Municipios de Valparaíso"),
                        ("EP031","Sociedad Agrícola y Servicios Isla de Pascua (SASIPA) - Empresas y Sociedades"),
                        ("AB041","Gobernación de Isla de Pascua - Interior y Seguridad Pública"),
                        ("AO101","Hospital San Juan de Dios de Los Andes - Salud"),
                        ("AB038","Gobernación de Los Andes - Interior y Seguridad Pública"),
                        ("MU152","Municipalidad de Los Andes - Municipios de Valparaíso"),
                        ("MU023","Municipalidad de Calle Larga - Municipios de Valparaíso"),
                        ("MU269","Municipalidad de Rinconada - Municipios de Valparaíso"),
                        ("MU284","Municipalidad de San Esteban - Municipios de Valparaíso"),
                        ("MU123","Municipalidad de La Ligua - Municipios de Valparaíso"),
                        ("AB035","Gobernación de Petorca - Interior y Seguridad Pública"),
                        ("MU016","Municipalidad de Cabildo - Municipios de Valparaíso"),
                        ("MU202","Municipalidad de Papudo - Municipios de Valparaíso"),
                        ("MU215","Municipalidad de Petorca - Municipios de Valparaíso"),
                        ("MU345","Municipalidad de Zapallar - Municipios de Valparaíso"),
                        ("MU253","Municipalidad de Quillota - Municipios de Valparaíso"),
                        ("AB039","Gobernación de Quillota - Interior y Seguridad Pública"),
                        ("AO099","Hospital San Martín de Quillota - Salud"),
                        ("MU116","Municipalidad de La Calera - Municipios de Valparaíso"),
                        ("MU102","Municipalidad de Hijuelas - Municipios de Valparaíso"),
                        ("MU118","Municipalidad de La Cruz - Municipios de Valparaíso"),
                        ("MU183","Municipalidad de Nogales - Municipios de Valparaíso"),
                        ("CF007","CFT de la Región de Valparaíso - Centro de Formación Técnica"),
                        ("MU280","Municipalidad de San Antonio - Municipios de Valparaíso"),
                        ("AO094","Hospital Claudio Vicuña de San Antonio - Salud"),
                        ("EP019","Empresa Portuaria San Antonio - Empresas y Sociedades"),
                        ("AB040","Gobernación de San Antonio - Interior y Seguridad Pública"),
                        ("MU001","Municipalidad de Algarrobo - Municipios de Valparaíso"),
                        ("MU029","Municipalidad de Cartagena - Municipios de Valparaíso"),
                        ("MU085","Municipalidad de El Quisco - Municipios de Valparaíso"),
                        ("MU086","Municipalidad de El Tabo - Municipios de Valparaíso"),
                        ("MU309","Municipalidad de Santo Domingo - Municipios de Valparaíso"),
                        ("AO021","Servicio de Salud Aconcagua - Salud"),
                        ("AB037","Gobernación de San Felipe - Interior y Seguridad Pública"),
                        ("AO054","Hospital de San Camilo - Salud"),
                        ("MU286","Municipalidad de San Felipe - Municipios de Valparaíso"),
                        ("MA016","Asociación de Municipalidades Quinta Región Cordillera - Asociación Municipal"),
                        ("MU032","Municipalidad de Catemu - Municipios de Valparaíso"),
                        ("MU143","Municipalidad de Llay Llay - Municipios de Valparaíso"),
                        ("MU201","Municipalidad de Panquehue - Municipios de Valparaíso"),
                        ("MU243","Municipalidad de Putaendo - Municipios de Valparaíso"),
                        ("MU307","Municipalidad de Santa María - Municipios de Valparaíso"),
                        ("CM019","Corporación Municipal de Quilpué - Corporaciones Municipales"),
                        ("AO097","Hospital de Quilpué - Salud"),
                        ("MU254","Municipalidad de Quilpué - Municipios de Valparaíso"),
                        ("AB090","Gobernación Provincial de Marga Marga - Interior y Seguridad Pública"),
                        ("MU139","Municipalidad de Limache - Municipios de Valparaíso"),
                        ("MU190","Municipalidad de Olmué - Municipios de Valparaíso"),
                        ("CM009","Corporación Municipal para el Desarrollo Social de Villa Alemana - Corporaciones Municipales"),
                        ("MU338","Municipalidad de Villa Alemana - Municipios de Valparaíso"),
                        ("AO046","SEREMI de Salud de OHiggins - Salud"),
                        ("MA021","Asociación de Municipalidades de la Región de OHiggins - Asociación Municipal"),
                        ("AB016","Intendencia de O Higgins - Interior y Seguridad Pública"),
                        ("CM008","Corporación Municipal de Rancagua (CORMUN) - Corporaciones Municipales"),
                        ("AB082","Gobierno Regional de OHiggins (Gore OHiggins) - Interior y Seguridad Pública"),
                        ("UN018","Universidad de Ohiggins - Universidades"),
                        ("MU260","Municipalidad de Rancagua - Municipios del Libertador General Bernardo OHiggins"),
                        ("AO088","Hospital Regional de Rancagua - Salud"),
                        ("AB042","Gobernación de Cachapoal - Interior y Seguridad Pública"),
                        ("AO024","Servicio de Salud OHiggins - Salud"),
                        ("AP008","SERVIU Región del Libertador Bernardo OHiggins - Vivienda y Urbanismo"),
                        ("MU051","Municipalidad de Codegua - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU054","Municipalidad de Coinco - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU059","Municipalidad de Coltauco - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU081","Municipalidad de Doñihue - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU100","Municipalidad de Graneros - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU134","Municipalidad de Las Cabras - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU160","Municipalidad de Machalí - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU164","Municipalidad de Malloa - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU176","Municipalidad de Mostazal - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU188","Municipalidad de Olivar - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU216","Municipalidad de Peumo - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU218","Municipalidad de Pichidegua - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU256","Municipalidad de Quinta de Tilcoco - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU266","Municipalidad de Rengo - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU267","Municipalidad de Requínoa - Municipios del Libertador General Bernardo OHiggins"),
                        ("CM051","Corporación Municipal de San Vicente - Corporaciones Municipales"),
                        ("MU303","Municipalidad de San Vicente de Tagua Tagua - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU219","Municipalidad de Pichilemu - Municipios del Libertador General Bernardo OHiggins"),
                        ("AB044","Gobernación de Cardenal Caro - Interior y Seguridad Pública"),
                        ("MU119","Municipalidad de La Estrella - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU141","Municipalidad de Litueche - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU165","Municipalidad de Marchige - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU180","Municipalidad de Navidad - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU203","Municipalidad de Paredones - Municipios del Libertador General Bernardo OHiggins"),
                        ("CM010","Corporación Municipal de San Fernando (CORMUSAF) - Corporaciones Municipales"),
                        ("AB043","Gobernación de Colchagua - Interior y Seguridad Pública"),
                        ("MU287","Municipalidad de San Fernando - Municipios del Libertador General Bernardo OHiggins"),
                        ("AO087","Hospital San Juan de Dios de San Fernando - Salud"),
                        ("MU039","Municipalidad de Chépica - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU044","Municipalidad de Chimbarongo - Municipios del Libertador General Bernardo OHiggins"),
                        ("PP006","Partido Movimiento Independiente Regionalista Agrario y Social (MIRAS) - Partidos Políticos"),
                        ("MU147","Municipalidad de Lolol - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU179","Municipalidad de Nancagua - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU199","Municipalidad de Palmilla - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU213","Municipalidad de Peralillo - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU223","Municipalidad de Placilla - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU237","Municipalidad de Pumanque - Municipios del Libertador General Bernardo OHiggins"),
                        ("MU305","Municipalidad de Santa Cruz - Municipios del Libertador General Bernardo OHiggins"),
                        ("UN012","Universidad de Talca (UTALCA) - Universidades"),
                        ("AO047","SEREMI de Salud del Maule - Salud"),
                        ("AB046","Gobernación de Talca - Interior y Seguridad Pública"),
                        ("MU312","Municipalidad de Talca - Municipios del Maule"),
                        ("AP009","SERVIU Región del Maule - Vivienda y Urbanismo"),
                        ("AB020","Intendencia del Maule - Interior y Seguridad Pública"),
                        ("AB083","Gobierno Regional del Maule (Gore Maule) - Interior y Seguridad Pública"),
                        ("AO085","Hospital Regional de Talca - Salud"),
                        ("AO025","Servicio de Salud Maule - Salud"),
                        ("MU064","Municipalidad de Constitución - Municipios del Maule"),
                        ("MU077","Municipalidad de Curepto - Municipios del Maule"),
                        ("MU087","Municipalidad de Empedrado - Municipios del Maule"),
                        ("MU169","Municipalidad de Maule - Municipios del Maule"),
                        ("MU206","Municipalidad de Pelarco - Municipios del Maule"),
                        ("MA028","Asociación de Municipalidades de la Región del Maule - Asociación Municipal"),
                        ("MU209","Municipalidad de Pencahue - Municipios del Maule"),
                        ("MU271","Municipalidad de Río Claro - Municipios del Maule"),
                        ("MU283","Municipalidad de San Clemente - Municipios del Maule"),
                        ("MU300","Municipalidad de San Rafael - Municipios del Maule"),
                        ("AB048","Gobernación de Cauquenes - Interior y Seguridad Pública"),
                        ("MU033","Municipalidad de Cauquenes - Municipios del Maule"),
                        ("MU037","Municipalidad de Chanco - Municipios del Maule"),
                        ("MU207","Municipalidad de Pelluhue - Municipios del Maule"),
                        ("MU078","Municipalidad de Curicó - Municipios del Maule"),
                        ("AB045","Gobernación de Curicó - Interior y Seguridad Pública"),
                        ("AO083","Hospital de Curicó - Salud"),
                        ("MU104","Municipalidad de Hualañé - Municipios del Maule"),
                        ("MU138","Municipalidad de Licantén - Municipios del Maule"),
                        ("MU174","Municipalidad de Molina - Municipios del Maule"),
                        ("MU262","Municipalidad de Rauco - Municipios del Maule"),
                        ("MU276","Municipalidad de Romeral - Municipios del Maule"),
                        ("MU278","Municipalidad de Sagrada Familia - Municipios del Maule"),
                        ("MU316","Municipalidad de Teno - Municipios del Maule"),
                        ("MU333","Municipalidad de Vichuquén - Municipios del Maule"),
                        ("MU140","Municipalidad de Linares - Municipios del Maule"),
                        ("CF002","CFT de la Región del Maule - Centro de Formación Técnica"),
                        ("AB047","Gobernación de Linares - Interior y Seguridad Pública"),
                        ("AO084","Hospital de Linares - Salud"),
                        ("MU055","Municipalidad de Colbún - Municipios del Maule"),
                        ("MU149","Municipalidad de Longaví - Municipios del Maule"),
                        ("MU204","Municipalidad de Parral - Municipios del Maule"),
                        ("MU268","Municipalidad de Retiro - Municipios del Maule"),
                        ("MU290","Municipalidad de San Javier - Municipios del Maule"),
                        ("MU337","Municipalidad de Villa Alegre - Municipios del Maule"),
                        ("MU342","Municipalidad de Yerbas Buenas - Municipios del Maule"),
                        ("MU061","Municipalidad de Concepción - Municipios del Bíobio"),
                        ("AB051","Gobernación de Concepción - Interior y Seguridad Pública"),
                        ("AO064","Hospital Guillermo Grant Benavente de Concepción - Salud"),
                        ("AO048","SEREMI de Salud del Bío Bío - Salud"),
                        ("AJ024","Servicio Local de Educación Pública Andalién Sur - Educación"),
                        ("AO027","Servicio de Salud Concepción - Salud"),
                        ("AP010","SERVIU Región del Bío Bío - Vivienda y Urbanismo"),
                        ("PP010","Partido Ecologista Verde (PEV) - Partidos Políticos"),
                        ("MA036","Asociación de Municipalidades de la Región del Biobío - Asociación Municipal"),
                        ("AK011","Corporación de Asistencia Judicial Región Bío Bío (CAJBIOBIO) - Justicia"),
                        ("AB019","Intendencia del Bío Bío - Interior y Seguridad Pública"),
                        ("MA010","Asociación de Municipalidades para el Desarrollo Económico Local - Asociación Municipal"),
                        ("PP046","Partido Pais - Partidos Políticos"),
                        ("AB084","Gobierno Regional del Bío Bío (Gore Bío Bío) - Interior y Seguridad Pública"),
                        ("UN013","Universidad del Bío Bío (UBB) - Universidades"),
                        ("AO062","Hospital San José de Coronel - Salud"),
                        ("MU068","Municipalidad de Coronel - Municipios del Bíobio"),
                        ("MU040","Municipalidad de Chiguayante - Municipios del Bíobio"),
                        ("MA043","Asociación de Municipalidades para la Preservación de la Biodiversidad en el Territorio de Nonguén y otros Ecosistemas - Asociación Municipal"),
                        ("MU090","Municipalidad de Florida - Municipios del Bíobio"),
                        ("MU106","Municipalidad de Hualqui - Municipios del Bíobio"),
                        ("EP010","Empresa Nacional del Carbón S.A. (ENACAR) - Empresas y Sociedades"),
                        ("AO063","Hospital de Lota - Salud"),
                        ("MU158","Municipalidad de Lota - Municipios del Bíobio"),
                        ("MU210","Municipalidad de Penco - Municipios del Bíobio"),
                        ("MU299","Municipalidad de San Pedro De La Paz - Municipios del Bíobio"),
                        ("MU306","Municipalidad de Santa Juana - Municipios del Bíobio"),
                        ("MU313","Municipalidad de Talcahuano - Municipios del Bíobio"),
                        ("EP020","Empresa Portuaria Talcahuano San Vicente - Empresas y Sociedades"),
                        ("AO028","Servicio de Salud Talcahuano - Salud"),
                        ("AO092","Hospital de las Higueras - Salud"),
                        ("AO091","Hospital de Tomé - Salud"),
                        ("MU324","Municipalidad de Tome - Municipios del Bíobio"),
                        ("MU105","Municipalidad de Hualpén - Municipios del Bíobio"),
                        ("AO030","Servicio de Salud Arauco - Salud"),
                        ("MU137","Municipalidad de Lebu - Municipios del Bíobio"),
                        ("AB052","Gobernación de Arauco - Interior y Seguridad Pública"),
                        ("MA015","Asociación de Municipalidades de la Provincia de Arauco - Asociación Municipal"),
                        ("MU011","Municipalidad de Arauco - Municipios del Bíobio"),
                        ("MA048","Asociación de Municipalidades de Arauco y Curanilahue - Asociación Municipal"),
                        ("MU027","Municipalidad de Cañete - Municipios del Bíobio"),
                        ("MU065","Municipalidad de Contulmo - Municipios del Bíobio"),
                        ("MU075","Municipalidad de Curanilahue - Municipios del Bíobio"),
                        ("MU151","Municipalidad de Los Alamos - Municipios del Bíobio"),
                        ("MU321","Municipalidad de Tirúa - Municipios del Bíobio"),
                        ("MU153","Municipalidad de Los Angeles - Municipios del Bíobio"),
                        ("MA038","Asociación de Municipalidades Bio Bio Centro - Asociación Municipal"),
                        ("AO029","Servicio de Salud Bíobío - Salud"),
                        ("AB050","Gobernación de Bíobío - Interior y Seguridad Pública"),
                        ("AO060","Hospital Víctor Ríos Ruiz de Los Angeles - Salud"),
                        ("MU010","Municipalidad de Antuco - Municipios del Bíobio"),
                        ("MA055","Asociación de Municipios para el Desarrollo Turístico de las Comunas de Cabrero Los Ángeles y Yumbel - Asociación Municipal"),
                        ("MU018","Municipalidad de Cabrero - Municipios del Bíobio"),
                        ("MU131","Municipalidad de Laja - Municipios del Bíobio"),
                        ("MU177","Municipalidad de Mulchén - Municipios del Bíobio"),
                        ("MU178","Municipalidad de Nacimiento - Municipios del Bíobio"),
                        ("MU181","Municipalidad de Negrete - Municipios del Bíobio"),
                        ("MU249","Municipalidad de Quilaco - Municipios del Bíobio"),
                        ("MU251","Municipalidad de Quilleco - Municipios del Bíobio"),
                        ("MU302","Municipalidad de San Rosendo - Municipios del Bíobio"),
                        ("MU304","Municipalidad de Santa Bárbara - Municipios del Bíobio"),
                        ("MA037","Asociación de Municipios Cordilleranos AMCORDI - Asociación Municipal"),
                        ("MU329","Municipalidad de Tucapel - Municipios del Bíobio"),
                        ("MU343","Municipalidad de Yumbel - Municipios del Bíobio"),
                        ("MU003","Municipalidad de Alto Biobío - Municipios del Bíobio"),
                        ("AB054","Gobernación de Cautín - Interior y Seguridad Pública"),
                        ("UN014","Universidad de La Frontera (UFRO) - Universidades"),
                        ("MU315","Municipalidad de Temuco - Municipios de La Araucanía"),
                        ("AO032","Servicio de Salud Araucanía Sur - Salud"),
                        ("AB085","Gobierno Regional de La Araucanía (Gore Araucanía) - Interior y Seguridad Pública"),
                        ("AI002","Corporación Nacional de Desarrollo Indígena (CONADI) - Desarrollo Social"),
                        ("AB012","Intendencia de La Araucanía - Interior y Seguridad Pública"),
                        ("AO049","SEREMI de Salud de La Araucanía - Salud"),
                        ("AO110","Hospital Dr. Hernán Henríquez Aravena de Temuco - Salud"),
                        ("MA026","Asociación de Municipalidades con Alcalde Mapuche - Asociación Municipal"),
                        ("AP011","SERVIU Región de la Araucanía - Vivienda y Urbanismo"),
                        ("MA033","Asociación de Municipios Costa Araucanía - Asociación Municipal"),
                        ("AJ020","Servicio Local de Educación Pública Costa Araucanía - Educación"),
                        ("MU028","Municipalidad de Carahue - Municipios de La Araucanía"),
                        ("MU071","Municipalidad de Cunco - Municipios de La Araucanía"),
                        ("MU076","Municipalidad de Curarrehue - Municipios de La Araucanía"),
                        ("MU091","Municipalidad de Freire - Municipios de La Araucanía"),
                        ("MU097","Municipalidad de Galvarino - Municipios de La Araucanía"),
                        ("MU099","Municipalidad de Gorbea - Municipios de La Araucanía"),
                        ("CF001","CFT de la Región de la Araucanía - Centro de Formación Técnica"),
                        ("MU136","Municipalidad de Lautaro - Municipios de La Araucanía"),
                        ("MU148","Municipalidad de Loncoche - Municipios de La Araucanía"),
                        ("MU172","Municipalidad de Melipeuco - Municipios de La Araucanía"),
                        ("MU184","Municipalidad de Nueva Imperial - Municipios de La Araucanía"),
                        ("MU194","Municipalidad de Padre Las Casas - Municipios de La Araucanía"),
                        ("MU214","Municipalidad de Perquenco - Municipios de La Araucanía"),
                        ("MU222","Municipalidad de Pitrufquén - Municipios de La Araucanía"),
                        ("MU230","Municipalidad de Pucón - Municipios de La Araucanía"),
                        ("MU277","Municipalidad de Saavedra - Municipios de La Araucanía"),
                        ("MU317","Municipalidad de Teodoro Schmidt - Municipios de La Araucanía"),
                        ("MU323","Municipalidad de Toltén - Municipios de La Araucanía"),
                        ("MU336","Municipalidad de Vilcún - Municipios de La Araucanía"),
                        ("MA045","Asociación de Municipalidades Turísticas lacustres AMTL - Asociación Municipal"),
                        ("MU339","Municipalidad de Villarrica - Municipios de La Araucanía"),
                        ("MU045","Municipalidad de Cholchol - Municipios de La Araucanía"),
                        ("AO057","Hospital Mauricio Heyermann de Angol - Salud"),
                        ("AO031","Servicio de Salud Araucanía Norte - Salud"),
                        ("MU008","Municipalidad de Angol - Municipios de La Araucanía"),
                        ("AB053","Gobernación de Malleco - Interior y Seguridad Pública"),
                        ("MU058","Municipalidad de Collipulli - Municipios de La Araucanía"),
                        ("MA008","Asociación de Municipalidades Malleco Norte AMMN - Asociación Municipal"),
                        ("MU072","Municipalidad de Curacautín - Municipios de La Araucanía"),
                        ("MU088","Municipalidad de Ercilla - Municipios de La Araucanía"),
                        ("MA058","Asociación de Municipalidades Cordilleranas de la Araucanía - Asociación Municipal"),
                        ("MU150","Municipalidad de Lonquimay - Municipios de La Araucanía"),
                        ("MU156","Municipalidad de Los Sauces - Municipios de La Araucanía"),
                        ("MU159","Municipalidad de Lumaco - Municipios de La Araucanía"),
                        ("MA003","Asociación de Municipalidades Nahuelbuta (AMN) - Asociación Municipal"),
                        ("MU241","Municipalidad de Purén - Municipios de La Araucanía"),
                        ("MU264","Municipalidad de Renaico - Municipios de La Araucanía"),
                        ("MU327","Municipalidad de Traiguén - Municipios de La Araucanía"),
                        ("MU334","Municipalidad de Victoria - Municipios de La Araucanía"),
                        ("AO056","Hospital de Victoria - Salud"),
                        ("AE031","CUARTO TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN METROPOLITANA - Hacienda"),
                        ("AE027","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DEL MAULE - Hacienda"),
                        ("AE030","TERCER TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN METROPOLITANA - Hacienda"),
                        ("AE021","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE MAGALLANES Y LA ANTÁRTICA CHILENA - Hacienda"),
                        ("AE020","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE LOS RÍOS - Hacienda"),
                        ("AE023","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE TARAPACÁ - Hacienda"),
                        ("AE029","SEGUNDO TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN METROPOLITANA - Hacienda"),
                        ("AE026","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DEL LOS LAGOS - Hacienda"),
                        ("AE024","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE VALPARAÍSO - Hacienda"),
                        ("AE017","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE AYSÉN DEL GENERAL CARLOS IBAÑÉZ DEL CAMPO - Hacienda"),
                        ("AE018","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE COQUIMBO - Hacienda"),
                        ("CM057","Corporación Municipal de Deportes Recreación y Cultura de Coquimbo - Corporaciones Municipales"),
                        ("AE014","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE ANTOFAGASTA - Hacienda"),
                        ("AE019","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE LA ARAUCANÍA - Hacienda"),
                        ("AE022","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE ÑUBLE Y REGIÓN DEL BIOBÍO - Hacienda"),
                        ("AE016","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE ATACAMA - Hacienda"),
                        ("AE028","PRIMER TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN METROPOLITANA - Hacienda"),
                        ("FU009","Corporación Regional de Desarrollo Productivo de la Región de Tarapacá - Fundaciones y corporaciones"),
                        ("AJ022","Servicio Local de Educación Pública Gabriela Mistral - Educación"),
                        ("AE015","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DE ARICA Y PARINACOTA - Hacienda"),
                        ("AE025","TRIBUNAL TRIBUTARIO Y ADUANERO DE LA REGIÓN DEL LIBERTADOR GENERAL BERNARDO OHIGGINS - Hacienda"),
                        ]

        for code, institution in institutions:
            yield scrapy.Request('https://www.portaltransparencia.cl/PortalPdT/pdtta/-/ta/'+code+'/PR/PCONT/', meta={'institution':institution})
    
    def parse(self, response):
        for year_link in response.css('a[target=_self]'):
            yield response.follow(year_link.xpath('@href').get(), 
                                  self.parse_year,
                                  meta={'institution':response.meta['institution']})

    def parse_year(self, response):
        for month_link in response.css('a[target=_self]'):
            yield response.follow(month_link.xpath('@href').get(), 
                                  self.parse_month,
                                  meta={'institution':response.meta['institution']})
        
    def parse_month(self, response):
        self.line_titles = response.xpath('//th//text()').getall()
        for line in response.xpath('//tr'):
            if len(line.xpath('td')) > 0:
                results = dict(zip(self.line_titles, line.xpath('td//text()').getall()))
                results.update({"Organismo": response.meta['institution']})
                yield results
        total_count_candidate = response.selector.re('rowCount:(\d+)')
        total_count = int(total_count_candidate[0]) if len(total_count_candidate)>0 else 0
        for start_page in range(100,total_count,100):
            yield scrapy.FormRequest.from_response(
                response,
                formid="A2248:form-visualizar",
                formdata={
                        "javax.faces.partial.ajax": "true",
                        "javax.faces.source": "A2248:form-visualizar:datosplantilla",
                        "javax.faces.partial.execute": "A2248:form-visualizar:datosplantilla",
                        "javax.faces.partial.render": "A2248:form-visualizar:datosplantilla",
                        "A2248:form-visualizar:datosplantilla": "A2248:form-visualizar:datosplantilla",
                        "A2248:form-visualizar:datosplantilla_pagination": "true",
                        "A2248:form-visualizar:datosplantilla_first": str(start_page),
                        "A2248:form-visualizar:datosplantilla_rows": str(min(100,total_count-start_page)),
                        "A2248:form-visualizar:datosplantilla_encodeFeature": "true"
                },
                url=response.css('input[name="javax.faces.encodedURL"]').xpath('@value').get(),
                callback=self.next_page,
                meta={'institution':response.meta['institution']})
        
        
    def next_page(self, response):
        parser = etree.XMLParser(strip_cdata=False)
        root = etree.fromstring(response.body, parser=parser, base_url=response.url)
        content = Selector(root=root).xpath('//text()').getall()
        inner_xml = content[0] if len(content)>0 else ""
        root2 = etree.fromstring("<newtable>" + inner_xml + "</newtable>")
        my_id = uuid.uuid4()
        self.selectors[my_id] = Selector(root=root2)
        for i,line in enumerate(self.selectors[my_id].xpath('//tr')):
            if len(line.xpath('td')) > 0:
                results = dict(zip(self.line_titles, line.xpath('td//text()').getall()))
                results.update({"Organismo": response.meta['institution']})
                yield results
            else:
                yield {"DEBUG": str(i) + ", len td is 0"}
        del self.selectors[my_id]
